<?php
$servername="localhost";
$username="root";
$password="";
$databasename="choiceup";
$con=mysqli_connect($servername,$username,$password,$databasename);
if(!$con)
{
    echo(mysqli_error($con));
}
?>